import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  parseBlueskyThread,
  parseFxTwitterResponse,
  parseYouTubeOEmbed,
  parseYtDlpMetadata
} from '../socialPosts/parsers.js'
import { parseSocialPostUrl } from '../socialPosts/urls.js'
import type { SocialPostTarget } from '../socialPosts/urls.js'

const fxTwitterFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/fxtwitter.json', import.meta.url), 'utf8')
)
const blueskyFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/bluesky-thread.json', import.meta.url), 'utf8')
)

const xTarget: SocialPostTarget = {
  platform: 'x',
  id: '665052190608723968',
  lookupKey: 'x:665052190608723968',
  canonicalUrl: 'https://x.com/i/status/665052190608723968',
  extractorUrl: 'https://x.com/i/status/665052190608723968',
  profile: 'starwars'
}

const blueskyTarget: SocialPostTarget = {
  platform: 'bluesky',
  id: '3mx7uc3l6i22k',
  lookupKey: 'bluesky:3mx7uc3l6i22k',
  canonicalUrl: 'https://bsky.app/profile/atproto.com/post/3mx7uc3l6i22k',
  extractorUrl: 'https://bsky.app/profile/atproto.com/post/3mx7uc3l6i22k',
  profile: 'atproto.com'
}

describe('social post parsers', () => {
  it('normalizes the recorded FxTwitter response without profile metadata', () => {
    expect(parseFxTwitterResponse(fxTwitterFixture, xTarget, 300)).toMatchObject({
      platform: 'x',
      id: '665052190608723968',
      authorHandle: 'starwars',
      authorName: 'Star Wars',
      createdAt: '2015-11-13',
      text: 'A new beginning is coming December 18. Watch the official 60 second #TV spot for #StarWars: #TheForceAwakens. https://amp.twimg.com/v/93ad3568-03d2-47b9-a57b-624b88693acd',
      photoCount: 0,
      videoCount: 0
    })
  })

  it('uses the quote text and first photo while counting all X media', () => {
    const post = parseFxTwitterResponse(
      {
        tweet: {
          id: '123',
          text: 'post',
          author: { screen_name: 'roka', name: 'Roka' },
          media: {
            photos: [{ url: 'https://pbs.twimg.com/photo-1' }, { url: 'https://pbs.twimg.com/photo-2' }],
            videos: [{ thumbnail_url: 'https://pbs.twimg.com/video-1' }]
          },
          quote: { text: 'quoted text', author: { screen_name: 'quotee', name: 'Quotee' } }
        }
      },
      { ...xTarget, id: '123', lookupKey: 'x:123' },
      100
    )

    expect(post).toMatchObject({
      text: 'post',
      quotedText: 'quoted text',
      quotedAuthorHandle: 'quotee',
      photoCount: 2,
      videoCount: 1,
      imageUrl: 'https://pbs.twimg.com/photo-1'
    })
  })

  it('normalizes a recorded Bluesky thread and external card', () => {
    expect(parseBlueskyThread(blueskyFixture, blueskyTarget, 300)).toMatchObject({
      platform: 'bluesky',
      id: '3mx7uc3l6i22k',
      authorHandle: 'atproto.com',
      authorName: 'AT Protocol Developers',
      createdAt: '2026-10-06',
      text: "We've added transcripts to Off Protocol. They're autogenerated using a local model with some QA, please let us know if something looks off. atproto.com/off-protocol",
      externalTitle: 'Off Protocol - AT Protocol',
      imageUrl:
        'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:ewvi7nxzyoun6zhxrhs64oiz/bafkreiaro4wxenxl3dd245otuv3g47ycxiik7rlrorsqmkii43th4jimeq'
    })
  })

  it('prefers Bluesky photo embeds and extracts video cover images and quotes', () => {
    const base = blueskyFixture.thread.post
    const images = parseBlueskyThread(
      {
        thread: {
          post: {
            ...base,
            embed: {
              $type: 'app.bsky.embed.recordWithMedia#view',
              record: {
                $type: 'app.bsky.embed.record#view',
                record: {
                  author: { handle: 'quotee.bsky.social' },
                  value: { text: 'quoted bsky post' }
                }
              },
              media: {
                $type: 'app.bsky.embed.images#view',
                images: [{ fullsize: 'https://cdn.bsky.app/img/one', alt: 'first' }]
              }
            }
          }
        }
      },
      blueskyTarget,
      100
    )
    const video = parseBlueskyThread(
      {
        thread: {
          post: {
            ...base,
            embed: { $type: 'app.bsky.embed.video#view', thumbnail: 'https://cdn.bsky.app/video-cover' }
          }
        }
      },
      blueskyTarget,
      100
    )

    expect(images).toMatchObject({ imageUrl: 'https://cdn.bsky.app/img/one', quotedText: 'quoted bsky post' })
    expect(video).toMatchObject({ imageUrl: 'https://cdn.bsky.app/video-cover', videoCount: 1 })
  })

  it('tolerates missing response fields and truncates post text', () => {
    expect(parseFxTwitterResponse({ tweet: {} }, xTarget, 4)).toMatchObject({
      text: '',
      authorHandle: '',
      photoCount: 0
    })
    expect(parseFxTwitterResponse({ tweet: { text: 'longer than cap' } }, xTarget, 4).text).toBe('long')
    expect(parseBlueskyThread({}, blueskyTarget, 4)).toBeNull()
  })

  // Field names as the live APIs return them: FxTwitter `replies`, Bluesky `replyCount`, yt-dlp `comment_count`.
  it('reads the reply count each source reports', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseFxTwitterResponse({ tweet: { replies: 193 } }, xTarget, 100).replyCount).toBe(193)
    expect(
      parseBlueskyThread({ thread: { post: { ...blueskyFixture.thread.post, replyCount: 4 } } }, blueskyTarget, 100)
        ?.replyCount
    ).toBe(4)
    expect(parseYtDlpMetadata({ title: 'Video', comment_count: 0 }, youtube, 100).replyCount).toBe(0)
  })

  it('leaves the reply count unknown when the source omits it', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseFxTwitterResponse({ tweet: {} }, xTarget, 100).replyCount).toBeNull()
    expect(parseBlueskyThread(blueskyFixture, blueskyTarget, 100)?.replyCount).toBeNull()
    expect(parseYtDlpMetadata({ title: 'Video' }, youtube, 100).replyCount).toBeNull()
    expect(parseYouTubeOEmbed({ title: 'Video' }, youtube, 100)?.replyCount).toBeNull()
  })

  it('parses yt-dlp upload dates in YYYYMMDD format', () => {
    const target = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseYtDlpMetadata({ title: 'Video', upload_date: '20261006' }, target, 100).createdAt).toBe('2026-10-06')
  })

  // Field shapes as yt-dlp returned them in production: YouTube's uploader_id already carries the @, Reddit's
  // channel_id is the subreddit, and TikTok's uploader_id is a numeric account id.
  it.each([
    [
      'https://youtu.be/jNQXAC9IVRw',
      { uploader: 'jawed', uploader_id: '@jawed', channel_id: 'UC4QobU6STFB0P71PMvOGN5A' },
      'jawed'
    ],
    ['https://www.reddit.com/r/videos/comments/6rrwyj/x/', { uploader: 'Antw87', channel_id: 'videos' }, 'Antw87'],
    [
      'https://www.tiktok.com/@pokemonlife22/video/7059698374567611694',
      { uploader: 'pokemonlife22', uploader_id: '6820838815978423302' },
      'pokemonlife22'
    ]
  ])('names the posting account for %s', (url, fields, handle) => {
    const target = parseSocialPostUrl(url)!

    expect(parseYtDlpMetadata({ title: 'Post', ...fields }, target, 100).authorHandle).toBe(handle)
  })
})
