import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  parseBlueskyThread,
  parseFxTwitterResponse,
  parseYouTubeOEmbed,
  parseYtDlpMetadata
} from '../socialPosts/parsers.js'
import { parseSocialPostUrl } from '../socialPosts/urls.js'
import type { SocialPostTarget } from '../socialPosts/urls.js'

const fxTwitterFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/fxtwitter.json', import.meta.url), 'utf8')
)
const blueskyFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/bluesky-thread.json', import.meta.url), 'utf8')
)
const fxTwitterVideoFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/fxtwitter-video.json', import.meta.url), 'utf8')
)
const redditVideoFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/reddit-video.json', import.meta.url), 'utf8')
)
const blueskyVideoFixture = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/social/bluesky-video-thread.json', import.meta.url), 'utf8')
)

const xTarget: SocialPostTarget = {
  platform: 'x',
  id: '665052190608723968',
  lookupKey: 'x:665052190608723968',
  canonicalUrl: 'https://x.com/i/status/665052190608723968',
  extractorUrl: 'https://x.com/i/status/665052190608723968',
  profile: 'starwars'
}

const blueskyTarget: SocialPostTarget = {
  platform: 'bluesky',
  id: '3mx7uc3l6i22k',
  lookupKey: 'bluesky:3mx7uc3l6i22k',
  canonicalUrl: 'https://bsky.app/profile/atproto.com/post/3mx7uc3l6i22k',
  extractorUrl: 'https://bsky.app/profile/atproto.com/post/3mx7uc3l6i22k',
  profile: 'atproto.com'
}

describe('social post parsers', () => {
  it('normalizes the recorded FxTwitter response without profile metadata', () => {
    expect(parseFxTwitterResponse(fxTwitterFixture, xTarget, 300)).toMatchObject({
      platform: 'x',
      id: '665052190608723968',
      authorHandle: 'starwars',
      authorName: 'Star Wars',
      createdAt: '2015-11-13',
      text: 'A new beginning is coming December 18. Watch the official 60 second #TV spot for #StarWars: #TheForceAwakens. https://amp.twimg.com/v/93ad3568-03d2-47b9-a57b-624b88693acd',
      photoCount: 0,
      videoCount: 0
    })
  })

  it('uses the quote text and first photo while counting all X media', () => {
    const post = parseFxTwitterResponse(
      {
        tweet: {
          id: '123',
          text: 'post',
          author: { screen_name: 'roka', name: 'Roka' },
          media: {
            photos: [{ url: 'https://pbs.twimg.com/photo-1' }, { url: 'https://pbs.twimg.com/photo-2' }],
            videos: [{ thumbnail_url: 'https://pbs.twimg.com/video-1' }]
          },
          quote: { text: 'quoted text', author: { screen_name: 'quotee', name: 'Quotee' } }
        }
      },
      { ...xTarget, id: '123', lookupKey: 'x:123' },
      100
    )

    expect(post).toMatchObject({
      text: 'post',
      quotedText: 'quoted text',
      quotedAuthorHandle: 'quotee',
      photoCount: 2,
      videoCount: 1,
      imageUrl: 'https://pbs.twimg.com/photo-1'
    })
  })

  it('normalizes a recorded Bluesky thread and external card', () => {
    expect(parseBlueskyThread(blueskyFixture, blueskyTarget, 300)?.post).toMatchObject({
      platform: 'bluesky',
      id: '3mx7uc3l6i22k',
      authorHandle: 'atproto.com',
      authorName: 'AT Protocol Developers',
      createdAt: '2026-10-06',
      text: "We've added transcripts to Off Protocol. They're autogenerated using a local model with some QA, please let us know if something looks off. atproto.com/off-protocol",
      externalTitle: 'Off Protocol - AT Protocol',
      imageUrl:
        'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:ewvi7nxzyoun6zhxrhs64oiz/bafkreiaro4wxenxl3dd245otuv3g47ycxiik7rlrorsqmkii43th4jimeq'
    })
  })

  it('prefers Bluesky photo embeds and extracts video cover images and quotes', () => {
    const base = blueskyFixture.thread.post
    const images = parseBlueskyThread(
      {
        thread: {
          post: {
            ...base,
            embed: {
              $type: 'app.bsky.embed.recordWithMedia#view',
              record: {
                $type: 'app.bsky.embed.record#view',
                record: {
                  author: { handle: 'quotee.bsky.social' },
                  value: { text: 'quoted bsky post' }
                }
              },
              media: {
                $type: 'app.bsky.embed.images#view',
                images: [{ fullsize: 'https://cdn.bsky.app/img/one', alt: 'first' }]
              }
            }
          }
        }
      },
      blueskyTarget,
      100
    )
    const video = parseBlueskyThread(
      {
        thread: {
          post: {
            ...base,
            embed: { $type: 'app.bsky.embed.video#view', thumbnail: 'https://cdn.bsky.app/video-cover' }
          }
        }
      },
      blueskyTarget,
      100
    )

    expect(images?.post).toMatchObject({ imageUrl: 'https://cdn.bsky.app/img/one', quotedText: 'quoted bsky post' })
    expect(video?.post).toMatchObject({ imageUrl: 'https://cdn.bsky.app/video-cover', videoCount: 1 })
  })

  it('selects the lowest bitrate MP4 variant from FxTwitter', () => {
    expect(parseFxTwitterResponse(fxTwitterVideoFixture, xTarget, 300)).toMatchObject({
      durationSec: 15.474,
      video: {
        url: 'https://video.twimg.com/amplify_video/820082508054179840/vid/240x240/b6ImBrQddohap5-6.mp4',
        bytes: null,
        headers: null,
        hasAudio: null
      }
    })
  })

  it('falls back from unusable FxTwitter variants to formats and then the primary URL', () => {
    const formats = parseFxTwitterResponse(
      {
        tweet: {
          media: {
            videos: [
              {
                variants: [{ url: 'https://media.example/playlist.m3u8', content_type: 'application/x-mpegURL' }],
                formats: [{ url: 'https://media.example/formats.mp4', container: 'mp4', bitrate: 10 }],
                url: 'https://media.example/primary.mp4',
                format: 'video/mp4'
              }
            ]
          }
        }
      },
      xTarget,
      100
    )
    const primary = parseFxTwitterResponse(
      {
        tweet: {
          media: {
            videos: [
              {
                variants: [{ url: 'https://media.example/playlist.m3u8', content_type: 'application/x-mpegURL' }],
                url: 'https://media.example/primary.mp4',
                format: 'video/mp4'
              }
            ]
          }
        }
      },
      xTarget,
      100
    )

    expect(formats.video?.url).toBe('https://media.example/formats.mp4')
    expect(primary.video?.url).toBe('https://media.example/primary.mp4')
  })

  it('selects the smallest supported Reddit video-only MP4 by bitrate', () => {
    const reddit = parseSocialPostUrl('https://www.reddit.com/r/videos/comments/abc123/a_post/')!
    const post = parseYtDlpMetadata(redditVideoFixture, reddit, 300)

    expect(post).toMatchObject({
      durationSec: 12,
      video: {
        url: 'https://v.redd.it/zv89llsvexdz/DASH_600_K',
        bytes: null,
        headers: { 'User-Agent': 'Mozilla/5.0', Accept: '*/*' },
        hasAudio: false
      }
    })
    expect(post.video?.url).not.toContain('.m3u8')
  })

  it('prefers a muxed yt-dlp MP4 over a smaller video-only MP4', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!
    const post = parseYtDlpMetadata(
      {
        title: 'Video',
        duration: 20,
        formats: [
          {
            url: 'https://media.example/silent.mp4',
            ext: 'mp4',
            protocol: 'https',
            vcodec: 'h264',
            acodec: 'none',
            filesize: 100,
            tbr: 200
          },
          {
            url: 'https://media.example/muxed.mp4',
            ext: 'mp4',
            protocol: 'https',
            vcodec: 'h264',
            acodec: 'aac',
            filesize: 200,
            tbr: 400
          }
        ]
      },
      youtube,
      100
    )

    expect(post.video).toMatchObject({ url: 'https://media.example/muxed.mp4', bytes: 200, hasAudio: true })
  })

  it('keeps approximate yt-dlp sizes and unknown audio status', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!
    const post = parseYtDlpMetadata(
      {
        title: 'Video',
        formats: [
          {
            url: 'https://media.example/video.mp4',
            ext: 'mp4',
            protocol: 'https',
            vcodec: 'h264',
            filesize_approx: 250,
            tbr: 100
          }
        ]
      },
      youtube,
      100
    )

    expect(post.video).toMatchObject({ url: 'https://media.example/video.mp4', bytes: 250, hasAudio: null })
  })

  it('leaves YouTube oEmbed duration and video unknown', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseYouTubeOEmbed({ title: 'Video' }, youtube, 100)).toMatchObject({ durationSec: null, video: null })
  })

  it('returns a Bluesky video blob for PDS resolution without putting it on the post', () => {
    const parsed = parseBlueskyThread(blueskyVideoFixture, blueskyTarget, 300)

    expect(parsed).toMatchObject({
      post: { videoCount: 1, durationSec: null, video: null },
      blueskyBlob: {
        did: 'did:plc:z72i7hdynmk6r22z27h6tvur',
        cid: 'bafkreifhuv36ji7vcq3tmdjltceyrfaat6vdccn2pklxf7j7dgsobdlgbm',
        bytes: 956983
      }
    })
    expect(parsed?.post).not.toHaveProperty('blueskyBlob')
  })

  it('reads a Bluesky video blob inside a recordWithMedia embed', () => {
    const record = blueskyVideoFixture.thread.post.record
    const parsed = parseBlueskyThread(
      {
        thread: {
          post: {
            ...blueskyVideoFixture.thread.post,
            record: {
              ...record,
              embed: { $type: 'app.bsky.embed.recordWithMedia', media: { video: record.embed.video } }
            }
          }
        }
      },
      blueskyTarget,
      300
    )

    expect(parsed?.blueskyBlob?.cid).toBe('bafkreifhuv36ji7vcq3tmdjltceyrfaat6vdccn2pklxf7j7dgsobdlgbm')
  })

  it('tolerates missing response fields and truncates post text', () => {
    expect(parseFxTwitterResponse({ tweet: {} }, xTarget, 4)).toMatchObject({
      text: '',
      authorHandle: '',
      photoCount: 0
    })
    expect(parseFxTwitterResponse({ tweet: { text: 'longer than cap' } }, xTarget, 4).text).toBe('long')
    expect(parseBlueskyThread({}, blueskyTarget, 4)).toBeNull()
  })

  // Field names as the live APIs return them: FxTwitter `replies`, Bluesky `replyCount`, yt-dlp `comment_count`.
  it('reads the reply count each source reports', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseFxTwitterResponse({ tweet: { replies: 193 } }, xTarget, 100).replyCount).toBe(193)
    expect(
      parseBlueskyThread({ thread: { post: { ...blueskyFixture.thread.post, replyCount: 4 } } }, blueskyTarget, 100)
        ?.post.replyCount
    ).toBe(4)
    expect(parseYtDlpMetadata({ title: 'Video', comment_count: 0 }, youtube, 100).replyCount).toBe(0)
  })

  it('leaves the reply count unknown when the source omits it', () => {
    const youtube = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseFxTwitterResponse({ tweet: {} }, xTarget, 100).replyCount).toBeNull()
    expect(parseBlueskyThread(blueskyFixture, blueskyTarget, 100)?.post.replyCount).toBeNull()
    expect(parseYtDlpMetadata({ title: 'Video' }, youtube, 100).replyCount).toBeNull()
    expect(parseYouTubeOEmbed({ title: 'Video' }, youtube, 100)?.replyCount).toBeNull()
  })

  it('parses yt-dlp upload dates in YYYYMMDD format', () => {
    const target = parseSocialPostUrl('https://youtu.be/abcdefghijk')!

    expect(parseYtDlpMetadata({ title: 'Video', upload_date: '20261006' }, target, 100).createdAt).toBe('2026-10-06')
  })

  // Field shapes as yt-dlp returned them in production: YouTube's uploader_id already carries the @, Reddit's
  // channel_id is the subreddit, and TikTok's uploader_id is a numeric account id.
  it.each([
    [
      'https://youtu.be/jNQXAC9IVRw',
      { uploader: 'jawed', uploader_id: '@jawed', channel_id: 'UC4QobU6STFB0P71PMvOGN5A' },
      'jawed'
    ],
    ['https://www.reddit.com/r/videos/comments/6rrwyj/x/', { uploader: 'Antw87', channel_id: 'videos' }, 'Antw87'],
    [
      'https://www.tiktok.com/@pokemonlife22/video/7059698374567611694',
      { uploader: 'pokemonlife22', uploader_id: '6820838815978423302' },
      'pokemonlife22'
    ],
    [
      'https://www.instagram.com/reel/DeMQyX2BTS0/',
      { uploader: 'Liew Zi Hin', uploader_id: '57371225913', channel: 'zihinliew' },
      'zihinliew'
    ]
  ])('names the posting account for %s', (url, fields, handle) => {
    const target = parseSocialPostUrl(url)!

    expect(parseYtDlpMetadata({ title: 'Post', ...fields }, target, 100).authorHandle).toBe(handle)
  })

  // yt-dlp gives an Instagram reel no duration, so Roka was told "1 photo" for a reel she could have watched.
  it('counts an Instagram reel with a playable video as a video, not a photo', () => {
    const target = parseSocialPostUrl('https://www.instagram.com/reel/DeMQyX2BTS0/')!
    const post = parseYtDlpMetadata(
      {
        title: 'Reel',
        thumbnail: 'https://scontent.cdninstagram.com/cover.jpg',
        formats: [
          {
            url: 'https://scontent.cdninstagram.com/reel.mp4',
            ext: 'mp4',
            protocol: 'https',
            vcodec: 'avc1',
            acodec: 'mp4a'
          }
        ]
      },
      target,
      100
    )

    expect(post).toMatchObject({ photoCount: 0, videoCount: 1 })
  })

  it('still counts an Instagram photo post as one photo', () => {
    const target = parseSocialPostUrl('https://www.instagram.com/p/AbCd123/')!

    expect(
      parseYtDlpMetadata({ title: 'Photo', thumbnail: 'https://scontent.cdninstagram.com/p.jpg' }, target, 100)
    ).toMatchObject({
      photoCount: 1,
      videoCount: 0
    })
  })
})
